### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by Zimormiz** [kakysha/HonorSpy#28]
Hi there! I did like 900HKs so far and the addon isnt working. I'd love to know my total estimated honor but I have a wonderful "Player Zîm not found in the table" :( I tried to delete WTF honorspy lua and bak but no improvment... What should I do?
![WoWScrnShot_111619_033910](https://user-images.githubusercontent.com/50952322/68986745-b366f200-0822-11ea-9e63-70fb870319f2.jpg)

**Comment by cdmichaelb** [comment]
Same issue. Same attempted resolutions. Character name 'Restoshaman' nothing special about my name.

**Comment by exus85** [comment]
Since this morning the tab is showing some names but the honor is wrong
![honorspy](https://user-images.githubusercontent.com/27153298/68991154-dfeb3000-085b-11ea-90ba-1141adb07180.jpg)

the db tab after few minutes:
![honorspy2](https://user-images.githubusercontent.com/27153298/68991314-ce0a8c80-085d-11ea-8c60-e34c872d1742.jpg)

**Comment by kakysha** [comment]
I'm in the process of investigating all of  this problems, addon just asks the server about honor of players, it didn't estimate honor. 

Still Blizzard delays the process, cause honor started to appear on Honor tab for players just 6 hrs ago.

**Comment by JYF** [comment]
GetInspectHonorData seems to return data for the last player you manually inspected instead of the one you mouseover

**Comment by kakysha** [comment]
@JYF true, and thats seems bugged to me, also players reporting that their "Honor" tab also reports strange values and messy HKs/honor for today and yesterday.
Either I need to adopt to this conditions or wait for Blizzard to fix this issues.

**Comment by moepman** [comment]
The "Honor" tab displays the last result it got back from the server and then after some delay updates (with what seems to be the right value).
Also: My Character still has all of its HKs listed under the today heading and nothing for yesterday/this week (which is really weird).

**Comment by Olorun** [comment]
Moepman, that's due to a bug from Blizzard - they made a bluepost about it, think it's fixed now and should be updated daily.

**Comment by sasha-koss** [comment]
![image](https://user-images.githubusercontent.com/4930994/68995623-ff03b500-088f-11ea-9ac2-b499ff7043c2.png)
Can confirm that the GetInspectHonorData is still reporting the honor points from the previous successful scan from Target Unit.
I had one Player targeted for some time and all newly added Players to the HonorSpy DB have the same honor points than my target.

**Comment by JYF** [comment]
Bluepost is a separate issue.

I found that if you call HasInspectHonorData in the INSPECT_HONOR_UPDATE event, you can check if the data is loaded and ignore that event. A second event is fired with the true data available. You can see there's a  0.5s update lag in the InspectUI  when you show the HonorTab.

if(not(HasInspectHonorData())) then
    return;
end

**Comment by kakysha** [comment]
@JYF still have a bug with copying another guys honor. Probably because `HasInspectHonorData()` reports `true` cause of old data still is there when you started inspecting new player

**Comment by Olorun** [comment]
Even after the fix, it's still not tracking everyone. I've been inspecting about 80 people in Hillsbrad but my it only shows 35 people right now.

**Comment by JYF** [comment]
Tried reproducing it, had one occurence of duplicate but then I tried inspecting manually and they had also duplicate in the Inspect GUI. Inspect API is a mess.

It takes ~1 second for the honor data to be retrieved, so mouseover is not very efficient for mass inspection if the mouse only stays on target a fraction of a second.

**Comment by sasha-koss** [comment]
Some entrys have exactly double the amount of honor points than they realy have when inspected.

**Comment by kakysha** [comment]
should be fixed for now
